# GRID INFO
GRID_WIDTH = 9
GRID_HEIGHT = 9

INNER_GRID_WIDTH = 8
INNER_GRID_HEIGHT = 8

# LAYOUTS (FOR LAYOUT SELECT COMMAND)
LAYOUT_SESSION = 0
LAYOUT_CUSTOM1 = 4
LAYOUT_CUSTOM2 = 5
LAYOUT_CUSTOM3 = 6
LAYOUT_DAW_FADERS = 13
LAYOUT_PROGRAMMER = 127

# CONTROL BUTTONS
CB_UPARROW = 91
CB_DOWNARROW = 92
CB_LEFTARROW = 93
CB_RIGHTARROW = 94
CB_SESSION = 95
CB_DRUMS = 96
CB_KEYS = 97
CB_USER = 98

# COLOR RELATED
H_MAX = 360
S_MAX = 100
V_MAX = 100
